name = "a0b_armv7m_selftest"
description = "A0B ARMv7M sefltest"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files = ["a0b_armv7m_selftest.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[configuration.values]
a0b_armv7m.fpu_extension = "VFPv4"
# FPU used on Cortex-M4, used for self testing.

[[depends-on]]
a0b_armv7m = "*"

[[pins]]
a0b_armv7m = { path='..' }
